# Usa una imagen base de Python (en este caso, la versión 3.9 slim)
FROM python:3.8.10

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*

# Copia el archivo del script MQTT_Connect_Flood.py desde tu máquina local al contenedor
COPY Recon_Ping_Sweep.py /app/Recon_Ping_Sweep.py

# Comando para ejecutar el script cuando el contenedor se inicie
CMD ["python3", "Recon_Ping_Sweep.py"]
