# Usa una imagen base de Python (en este caso, la versión 3.9 slim)
FROM python:3.8.10

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo del script TCP_Connect_Flood.py desde tu máquina local al contenedor
COPY TCP_Connect_Flood.py /app/TCP_Connect_Flood.py

# Instala las dependencias necesarias
RUN apt-get update && \
    apt-get install -y iproute2 iputils-ping net-tools && \
    apt-get clean

# Comando para ejecutar el script cuando el contenedor se inicie
CMD ["python3", "TCP_Connect_Flood.py"]
