# Usa una imagen base de Python (en este caso, la versión 3.9 slim)
FROM python:3.8.10

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

RUN apt update && apt install -y iproute2 iputils-ping && pip install scapy

# Copia el archivo del script MQTT_Connect_Flood.py desde tu máquina local al contenedor
COPY ARP_Spoofing.py /app/ARP_Spoofing.py

# Comando para ejecutar el script cuando el contenedor se inicie
CMD ["python3", "ARP_Spoofing.py"]
